//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQRSExample.Data.Sql.StarterDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialNumber()
        {
            this.WorkCenter = new HashSet<WorkCenter>();
        }
    
        public int Poid { get; set; }
        public string Id { get; set; }
        public int MaxQuantity { get; set; }
        public int MinQuantity { get; set; }
        public bool Renner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkCenter> WorkCenter { get; set; }
    }
}
