//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQRSExample.Data.Sql.StarterDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StarterDbEntities : DbContext
    {
        public StarterDbEntities()
            : base("name=StarterDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MaterialNumber> MaterialNumber { get; set; }
        public virtual DbSet<Plant> Plant { get; set; }
        public virtual DbSet<WorkCenter> WorkCenter { get; set; }
    }
}
